Feature/create rateio
desenvolvendome-14/contas pull request #31
Opened 2021-09-30 11:32 UTC by hemershon

Removi a branch anterior estava com muitos erros essa é um nova branch

2021-10-12 02:13 UTC, LukasPol requested changes

2021-10-12 02:13 UTC, LukasPol commented on app/models/account_plan.rb
> -  has_many :bills
Tem q ter essa linha

2021-10-12 02:13 UTC, LukasPol commented on app/models/invoice_receivable.rb
> +class InvoiceReceivable < ApplicationRecord
Esse model não existe

2021-10-12 02:13 UTC, LukasPol commented on app/models/invoice_receivable.rb
> +class InvoiceReceivable < ApplicationRecord
INvoice Receivable é um bill com type_bill = invoice_receivable

2021-10-12 02:13 UTC, LukasPol commented on app/models/rateio.rb
> +  validates :code, :story, presence: true
esse story seria observação??
e code oq é??

2021-10-12 02:13 UTC, LukasPol commented on db/migrate/20211002023517_create_invoice_receivables.rb
> +# frozen_string_literal: true
Não existe

2021-10-12 02:13 UTC, LukasPol commented on spec/factories/account_plans.rb
> +# == Schema Information
tenta deixar esse `schema information` só no model, não nos testes

2021-10-12 02:13 UTC, LukasPol commented on spec/factories/account_plans.rb
> +# == Schema Information
remover dos factories e dos teste de models

2021-10-12 02:13 UTC, LukasPol commented on app/models/invoice_receivable.rb
> +class InvoiceReceivable < ApplicationRecord
`rails d model InvoiceReceivable`

2021-10-12 02:13 UTC, LukasPol commented on app/models/invoice_receivable.rb
> +class InvoiceReceivable < ApplicationRecord
para deletar

2021-10-12 08:33 UTC, LukasPol commented on app/models/rateio.rb
> +  belongs_to :invoice
oq seria esse `bio_id` e `invoice` ??

2021-10-12 08:34 UTC, LukasPol commented on app/models/bill.rb
>  class Bill < ApplicationRecord
FAltou colocar `has_many :rateios`

2021-10-13 08:42 UTC, hemershon commented on app/models/rateio.rb
> +  validates :code, :story, presence: true
https://marvelapp.com/project/5842910/screen/81963942

o code faz parte do prototipo e a história

2021-10-15 23:36 UTC, merged