feat(type_charge) list description
desenvolvendome-14/contas pull request #67
Opened 2021-11-15 17:50 UTC by hemershon

2021-11-16 09:04 UTC, LukasPol requested changes

2021-11-16 09:04 UTC, LukasPol commented on app/controllers/api/v1/type_charge_controller.rb
> +      before_action :set_typeCharge, only: %i[show update destroy]
??
Pra q isso?

2021-11-17 02:36 UTC, hemershon commented on app/controllers/api/v1/type_charge_controller.rb
> +      before_action :set_typeCharge, only: %i[show update destroy]
Removi o before_action

2021-11-17 02:36 UTC, hemershon commented on spec/requests/api/v1/type_charge_spec.rb
>    describe "GET /index" do
Adicionei os teste de request

2021-11-17 08:33 UTC, LukasPol requested changes

2021-11-17 08:33 UTC, LukasPol commented on config/routes.rb
>        resources :cost_center
remover esssa linha do `cost_center`

2021-11-17 12:28 UTC, hemershon commented on config/routes.rb
>        resources :cost_center
Removido!

2021-11-17 12:36 UTC, hemershon commented on config/routes.rb
>        resources :cost_center
removido

2021-11-17 13:18 UTC, LukasPol requested changes

2021-11-17 13:18 UTC, LukasPol commented on app/controllers/api/v1/type_charges_controller.rb
> +    class TypeChargesController < ApplicationController
dois arquivos??
`type_charges` e `type_charge` ?

2021-11-17 13:18 UTC, LukasPol commented on app/controllers/api/v1/type_charges_controller.rb
> +    class TypeChargesController < ApplicationController
o certo é no plural

Nos spec tem q ter ser no plural tbm

2021-11-17 14:58 UTC, LukasPol requested changes

2021-11-17 14:58 UTC, LukasPol commented on config/routes.rb
> +      resources :type_charges
add `only: :index`

2021-11-17 14:58 UTC, LukasPol commented on app/views/api/v1/type_charges/_type_charges.json.jbuilder
> +json.extract! type_charges, :id, :description, :created_at, :updated_at
nome deste arquivo deve ser no singular (`_type_charge.json.jbuilder`) pois é referente a um registro e não vários

2021-11-17 14:58 UTC, LukasPol commented on app/views/api/v1/type_charges/_type_charges.json.jbuilder
> +json.extract! type_charges, :id, :description, :created_at, :updated_at
Outra q o nome da variavel tbm tem q ser no singular `type_charge`

** Mudar no arq index tbm

2021-12-15 09:31 UTC, closed without merging